### ISSUE TITLE
请问服务器一定要在国内吗

### ISSUE THREAD

**Issue by ReneXiong** [mu228/no#1]
请问服务器一定要是中国大陆境内的吗？另外，这个脚本方法的原理是什么？对三网都有用吗？

**Comment by mrcosir** [comment]
😂这个是我自用的！没想到你还能找到！

**Comment by ReneXiong** [comment]
于是就回答下这个问题呗？

**Comment by mrcosir** [comment]
嗯.中国大陆的最好.速度快.

**Comment by ReneXiong** [comment]
我希望能同时兼顾免流和fq，能不能放在香港或者日本之类的地方？会不会影响免流？

**Comment by ghost** [comment]
怎么安装，能有详细一点的教程吗？

**Comment by ghost** [comment]
我的是在国外，参考的是sbwml.cn的 可以 。

2016-05-26 19:24 GMT+08:00 聂人狂 notifications@github.com:
